# -*- coding: utf-8 -*-
"""house_prediction_web_app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RxK0K9DJ6Gr0WxUpOdFM6FvUADbaqPYQ
"""

import numpy as np
import pickle
import streamlit as st

loaded_house_price_model=pickle.load(open(house_price_predictor.sav,'rb'))

def house_price_prediction(input_data):
  input_data_as_numpy_array=np.asarray(input_data)
  input_data_reshaped=input_data_as_numpy_array.reshape(1,-1)
  prediction=house_price_predictor.predict(input_data_reshaped)
  print (f'The predicted price of the house is {prediction} $')

def main ():
  st.title ('House Price Prediction')
  SquareFeet=st.text_input('How much Square Feets does the house have: ')
  Bedrooms=st.text_input('How many bedrooms does the house have: ')
  Bathrooms=st.text_input('How many bathrooms does the house have: ')
  Neighborhood=st.text_input('In which neighborhood is located the house ("Suburb":0,"Rural" :1,"Urban":2): ')
  YearBuilt=st.text_input('When was the house built (From 1950 to 2020): ')

  diagnosis=''
  if st.button('House Price Prediction'):
    diagnosis=house_price_prediction([SquareFeet,Bedrooms,Bathrooms,Neighborhood,YearBuilt])
  st.success(diagnosis)

st.write(st.__version__)
st.write(np.__version__)
st.write(pickle.__version__)

if __name__=='__main__':
  main()


